package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

func CleanCMD() *cobra.Command {
	return &cobra.Command{
		Use:   "clean",
		Short: "clean all .out log files",
		Long:  "clean all .out log files generated by dev command",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Println("==================== 开始清理日志文件 ====================")

			// 获取当前目录下所有 .out 文件
			matches, err := filepath.Glob("*.out")
			if err != nil {
				panic(fmt.Sprintf("❌ 查找 .out 文件失败: %v", err))
			}

			if len(matches) == 0 {
				fmt.Println("✅ 没有找到需要清理的 .out 文件")
				return
			}

			// 删除所有找到的 .out 文件
			deletedCount := 0
			for _, file := range matches {
				err := os.Remove(file)
				if err != nil {
					fmt.Printf("⚠️  删除 %s 失败: %v\n", file, err)
				} else {
					fmt.Printf("🗑️  已删除: %s\n", file)
					deletedCount++
				}
			}

			fmt.Printf("\n✅ 清理完成！共删除 %d 个日志文件\n", deletedCount)
		},
	}
}
